Documents/Banks/Alliance/CC/MPGS/Controllers/PaymentApiController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using gateway_csharp_sample_code.Models;
using Microsoft.Extensions.Options;
using gateway_csharp_sample_code.Gateway;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using gateway_csharp_sample_code.Utils;
using Microsoft.AspNetCore.WebUtilities;
using System.Text;
using System.Runtime.InteropServices;

namespace gateway_csharp_sample_code.Controllers

{
    /// <summary>
    /// Controller responsible to centralize the process and result methods
    /// </summary>
    public class PaymentApiController : BaseController
    {

        public PaymentApiController(IOptions<GatewayApiConfig> gatewayApiConfig, GatewayApiClient gatewayApiClient, NVPApiClient nvpApiClient, ILogger<PaymentApiController> logger) : 
        base (gatewayApiConfig, gatewayApiClient, nvpApiClient, logger)
        {
        }

        /// <summary>
        /// This method processes the API request for server-to-server operations. These are operations that would not commonly be invoked via a user interacting with the browser, but a system event (CAPTURE, REFUND, VOID).
        /// <summary>
        /// <param name="gatewayApiRequest">contains info on how to construct API call</param>
        /// <returns>IActionResult for api response page or error page</returns>
        [HttpPost("process"), HttpGet("process") ]
        public IActionResult Process(GatewayApiRequest gatewayApiRequest)
        {
            Logger.LogInformation($"PaymentApiController Process action gatewayApiRequest {JsonConvert.SerializeObject(gatewayApiRequest)}");

            gatewayApiRequest.GatewayApiConfig = GatewayApiConfig;

            //retrieve order doesnt require transaction information on the url
            if ("RETRIEVE_ORDER" == gatewayApiRequest.ApiOperation)
            {
                gatewayApiRequest.buildOrderUrl();
            }
            else
            {
                gatewayApiRequest.buildRequestUrl();
            }

            gatewayApiRequest.buildPayload();

            string response = GatewayApiClient.SendTransaction(gatewayApiRequest);

            buildViewData(gatewayApiRequest, response);

            return View(ViewList.GetValueOrDefault("ApiResponse"));
        }

        /// <summary>
        /// This method calls the INTIATE_BROWSER_PAYMENT operation, which returns a URL to the provider's website. The user is redirected to this URL, where the purchase is completed.
        /// </summary>
        /// <param name="gatewayApiRequest">contains info on how to construct API call</param>
        /// <returns>IActionResult for api response page or error page</returns>
        [HttpPost("processHostedSession")]
        public IActionResult ProcessHostedSession([FromBody] GatewayApiRequest gatewayApiRequest)
        {
            Logger.LogInformation($"PaymentApiController ProcessHostedSession action gatewayApiRequest {JsonConvert.SerializeObject(gatewayApiRequest)}");

            gatewayApiRequest.GatewayApiConfig = GatewayApiConfig;
            gatewayApiRequest.buildRequestUrl();
            gatewayApiRequest.buildPayload();

            string response = GatewayApiClient.SendTransaction(gatewayApiRequest);

            buildViewData(gatewayApiRequest, response);

            return View(ViewList.GetValueOrDefault("ApiResponse"));
        }

        [HttpPost("tokenize")]
        public IActionResult tokenize([FromBody] GatewayApiRequest gatewayApiRequest)
        {
            Logger.LogInformation($"PaymentApiController ProcessHostedSession action gatewayApiRequest {JsonConvert.SerializeObject(gatewayApiRequest)}");

            //update session with order details
            GatewayApiRequest gatewayUpdateSessionRequest = new GatewayApiRequest(GatewayApiConfig);
            gatewayUpdateSessionRequest.ApiMethod = GatewayApiClient.PUT;

            //update the url appending session id
            gatewayUpdateSessionRequest.buildSessionRequestUrl(gatewayApiRequest.SessionId);

            gatewayUpdateSessionRequest.OrderId = gatewayApiRequest.OrderId;
            gatewayUpdateSessionRequest.OrderCurrency = gatewayApiRequest.OrderCurrency;
            gatewayUpdateSessionRequest.OrderAmount = gatewayApiRequest.OrderAmount;

            //build payload with order info
            gatewayUpdateSessionRequest.buildPayload();

            String response = GatewayApiClient.SendTransaction(gatewayUpdateSessionRequest);

            Logger.LogInformation($"Tokenize updated session {response}");

            //validate transaction response
            if (JsonHelper.isErrorMessage(response))
            {
                return View("Error", ErrorViewModel.toErrorViewModel(getRequestId(), response));
            }

            //generate token
            GatewayApiRequest gatewayGenerateTokenRequest = new GatewayApiRequest(GatewayApiConfig);
            gatewayGenerateTokenRequest.SessionId = gatewayApiRequest.SessionId;
            gatewayGenerateTokenRequest.ApiMethod = GatewayApiClient.POST;
            gatewayGenerateTokenRequest.buildPayload();
            gatewayGenerateTokenRequest.buildTokenUrl();

            response = GatewayApiClient.SendTransaction(gatewayGenerateTokenRequest);

                //validate token response
                if (JsonHelper.isErrorMessage(response))
                {
                    return View("Error", ErrorViewModel.toErrorViewModel(getRequestId(), response));
                }

            //convert json to model
            TokenResponse tokenResponse = TokenResponse.ToTokenResponse(response);

            //payment with token
            GatewayApiRequest gatewayGeneratePaymentRequest = new GatewayApiRequest(GatewayApiConfig);
            gatewayGeneratePaymentRequest.ApiOperation = "PAY";
            gatewayGeneratePaymentRequest.ApiMethod = GatewayApiClient.PUT;

            gatewayGeneratePaymentRequest.Token = tokenResponse.Token;
            gatewayGeneratePaymentRequest.SessionId = gatewayApiRequest.SessionId;
            gatewayGeneratePaymentRequest.OrderId = gatewayApiRequest.OrderId;
            gatewayGeneratePaymentRequest.TransactionId = gatewayApiRequest.TransactionId;

            gatewayGeneratePaymentRequest.buildPayload();
            gatewayGeneratePaymentRequest.buildRequestUrl();

            response = GatewayApiClient.SendTransaction(gatewayGeneratePaymentRequest);

            buildViewData(gatewayGeneratePaymentRequest, response);

            return View(ViewList.GetValueOrDefault("ApiResponse"));
        }

        /// <summary>
        /// This method receives the callback from the Hosted Checkout redirect. It looks up the order using the RETRIEVE_ORDER operation and
        /// displays either the receipt or an error page.
        /// </summary>
        /// <param name="orderId">needed to retrieve order</param>
        /// <param name="result">Result of Hosted Checkout operation (success or error) - sent from hostedCheckout.html complete() callback</param>
        /// <returns>IActionResult for hosted checkout receipt page or error page</returns>
        [HttpGet("hostedCheckout/{orderId}/{result}"), HttpGet("hostedCheckout/{orderId}/{result}/{sessionId}")]
        public IActionResult HostedCheckoutReceipt([FromRoute(Name = "orderId")] string orderId, [FromRoute(Name = "result")] string result, [FromRoute(Name = "sessionId")] string sessionId)
        {
            Logger.LogInformation($"PaymentApiController HostedCheckoutReceipt action orderId {orderId} result {result} sessionId {sessionId}");

            if (result == "SUCCESS")
            {
                GatewayApiRequest gatewayApiRequest = new GatewayApiRequest(GatewayApiConfig)
                {
                    ApiOperation = "RETRIEVE_ORDER",
                    OrderId = orderId,
                    ApiMethod = GatewayApiClient.GET
                };

                gatewayApiRequest.buildOrderUrl();


                string response = GatewayApiClient.SendTransaction(gatewayApiRequest);

                Logger.LogInformation($"Hosted checkout retrieve order response {response}");

                //parse response
                TransactionResponseModel transactionResponseModel = null;
                try
                {
                    transactionResponseModel = TransactionResponseModel.toTransactionResponseModel(response);
                }
                catch (Exception e)
                {
                    Logger.LogError($"Hosted Checkout Receipt error : {JsonConvert.SerializeObject(e)}");

                    return View("Error", new ErrorViewModel
                    {
                        RequestId = getRequestId(),
                        Cause = e.InnerException != null ? e.InnerException.StackTrace : e.StackTrace,
                        Message = e.Message
                    });
                }

                return View(ViewList.GetValueOrDefault("Receipt"), transactionResponseModel);
            }
            else
            {
                Logger.LogError($"The payment was unsuccessful {result}");
                return View("Error", new ErrorViewModel
                {
                    RequestId = getRequestId(),
                    Cause = "Payment was unsuccessful",
                    Message = "There was a problem completing your transaction."
                });
            }
        }

        /// <summary>
        /// This method handles the response from the CHECK_3DS_ENROLLMENT operation. If the card is enrolled, the response includes the HTML for the issuer's authentication form, to be injected into secureIdPayerAuthenticationForm.html.
        /// Otherwise, it displays an error.
        /// <summary> 

Documents/Banks/Alliance/CC/MPGS/Views/Payment/ApiResponse.cshtml
<div class="col-9 pl-4">
    <h3>@ViewBag.Operation Operation</h3>
    <p class="endpoint">@ViewBag.Method @ViewBag.RequestUrl</p>

    <h5>Payload</h5>
    <pre>@ViewBag.Payload</pre>

    <h5>Response</h5>
    <pre>@ViewBag.Response</pre>
</div>

Documents/Banks/Alliance/CC/MPGS/Views/Payment/Capture.cshtml
@using gateway_csharp_sample_code.Gateway
@model gateway_csharp_sample_code.Gateway.GatewayApiRequest

<div class="col-9">
    <div class="row">
        <form class="col-12 form-horizontal" asp-controller="PaymentApi" asp-action="process" method="post">
            <h3>Capture</h3>
            <div class="alert alert-warning" role="alert">
                This API operation is typically not a browser initiated action. However, we are calling this action from browser only as a reference to get an idea of how it can be done through your application.
            </div>
            <div class="mb-4">
                <input asp-for="TransactionId" id="transactionId" type="hidden" />
                <input asp-for="ApiOperation" id="apiOperation" type="hidden" />
                <input asp-for="ApiMethod" id="apiMethod" type="hidden" />
                <div class="form-group">
                    <label for="order-id">Order ID</label>
                     <input asp-for="OrderId" id="order-id" type="text" placeholder="[Order ID from existing authorization]" class="form-control input-md" required=""/>
                </div>
                <div class="form-group">
                    <label for="transaction-amount">Amount</label>
                    <input asp-for="TransactionAmount" id="transaction-amount" type="text" placeholder="[Amount less than or equal to the authorized amount]" class="form-control input-md" required=""/>                      
                </div>
                <div class="form-group">
                    <label for="transaction-currency">Currency</label>
                    <input asp-for="TransactionCurrency" id="transaction-currency" type="text" placeholder="[Currency from existing authorization]" class="form-control input-md" required=""/>
                </div>
                <div class="form-group">
                    <button id="process" name="process" class="btn btn-primary">Process Capture</button>
                </div>
            </div>
        </form>
    </div> <!-- row -->
</div>

Documents/Banks/Alliance/CC/MPGS/Views/Payment/HostedCheckout.cshtml
<div class="col-9">
    <div class="row">
        <div class="contents col-12">
            <div class="col-md-12">
                <h3>Hosted Checkout</h3>
                <p>The Hosted Checkout model allows you to collect payment details from your payer through an interaction hosted and displayed by the Payment Gateway. This means you aren't responsible for handling sensitive PCI data.</p>
                <p>Hosted Checkout can be implemented as:</p>
                <div class="container mt-5">
                    <div class="row">
                        <div class="col">
                            <h5>Lightbox</h5>
                            <ul class="my-4">
                                <li>Opens modal; doesn't redirect away from merchant site</li>
                                <li>Seamless checkout experience</li>
                            </ul>
                            <input id="lightbox-with-session" type="button" class="btn btn-primary mr-2" value="Pay with Lightbox" onclick="Checkout.showLightbox();" />
                        </div>
                        <div class="col">
                            <h5>Payment Page</h5>
                            <ul class="my-4">
                                <li>Redirects to Gateway-hosted payment page</li>
                                <li>Ideal if your site isn't SSL-secured</li>
                            </ul>
                            <input id="page-with-session" type="button" class="btn btn-primary" value="Pay with Payment Page" onclick="Checkout.showPaymentPage();" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- row -->
</div>
<script src="@ViewBag.CheckoutJsUrl"
        data-error="errorCallback"
        data-cancel="cancelCallback"
        data-beforeRedirect="beforeRedirect"
        data-afterRedirect="afterRedirect"
        data-complete="completeCallback"> 
</script>
<script>

    /*<![CDATA[*/
        var merchantId = "@ViewBag.MerchantId";
        var sessionId = "@ViewBag.CheckoutSession.Id";
        var sessionVersion = "@ViewBag.CheckoutSession.Version";
        var successIndicator = "@ViewBag.CheckoutSession.SuccessIndicator";
        var orderId = "@ViewBag.OrderId";
        var currency = "@ViewBag.Currency";
    /*]]>*/
        var resultIndicator = null;

    // This method preserves the current state of successIndicator and orderId, so they're not overwritten when we return to this page after redirect
    function beforeRedirect() {
    console.log("beforeRedirect");
        return {
            successIndicator: successIndicator,
            orderId: orderId
        };
    }

    // This method is specifically for the full payment page option. Because we leave this page and return to it, we need to preserve the
    // state of successIndicator and orderId using the beforeRedirect/afterRedirect option
    function afterRedirect(data) {
        console.log("afterRedirect", data);
        // Compare with the resultIndicator saved in the completeCallback() method
        if(resultIndicator === "CANCELED"){
            return;
        }    
        else if (resultIndicator) {
            var result = (resultIndicator === data.successIndicator) ? "SUCCESS" : "ERROR";
            window.location.href = "/hostedCheckout/" + data.orderId + "/" + result;
        }
        else {
            successIndicator = data.successIndicator;
            orderId = data.orderId;
            sessionId = data.sessionId;
            sessionVersion = data.sessionVersion;
            merchantId = data.merchantId;

            window.location.href = "/hostedCheckout/" + data.orderId + "/" + data.successIndicator + "/" + data.sessionId;
        }
    
    }

    function errorCallback(error) {
        var message = JSON.stringify(error);
        $("#loading-bar-spinner").hide();
        var $errorAlert = $('#error-alert');
        console.log(message);
        $errorAlert.append("<p>" + message + "</p>");
        $errorAlert.show();
    }
    function cancelCallback() {
        console.log('Payment cancelled');
        resultIndicator = "CANCELED" ;
        // Reload the page to generate a new session ID - the old one is out of date as soon as the lightbox is invoked
        window.location.reload(true);
    }

    // This handles the response from Hosted Checkout and redirects to the appropriate endpoint
    function completeCallback(response) {
        console.log("completeCallback", response);
        // Save the resultIndicator
        resultIndicator = response;
        var result = (resultIndicator === successIndicator) ? "SUCCESS" : "ERROR";

        window.location.href = "/hostedCheckout/" + orderId + "/" + result;
    }

    Checkout.configure({
        merchant: merchantId,
        order: {
            amount: function() {
                //Dynamic calculation of amount
                return 80 + 20;
            },
            currency: currency,
            description: 'Ordered goods'
        },
        session: {
            id: sessionId
        },
        interaction: {
            merchant: {
                name: 'Merchant Name',
                address: {
                    line1: '200 Sample St',
                    line2: '1234 Example Town'
                }
            }
        }
    });
</script>

Documents/Banks/Alliance/CC/MPGS/Views/Payment/MasterpassButton.cshtml
<script src="https://sandbox.masterpass.com/lightbox/Switch/integration/MasterPass.client.js"></script>

<script type="text/javascript">

    //set Masterpass js variables
    var requestToken = '@(ViewBag.requestToken)';
    var merchantCheckoutId = '@(ViewBag.merchantCheckoutId)';
    var allowedCardTypes = '@(ViewBag.allowedCardTypes)';

    console.log("RequestToken: " + requestToken) ;
    console.log("MerchantCheckoutId : " + merchantCheckoutId ) ;
    console.log("AllowedCardTypes : " + allowedCardTypes ) ;


    function launchMasterpass() {
        // INITIALIZE and INVOKE THE MASTERPASS LIGHTBOX
        MasterPass.client.checkout({
            "version":"v6",
            "successCallback": onSuccessfulCheckout,
            "cancelCallback": onCancel,
            "failureCallback": onFailure,
            // USE PARAMETERS FROM THE OPEN WALLET RESPONSE
            "requestToken": requestToken,
            "merchantCheckoutId": merchantCheckoutId,
            "allowedCardTypes": allowedCardTypes
        });
    }

    // RETRIEVE PARAMETERS FROM THE LIGHTBOX INTERACTION
    function onSuccessfulCheckout(data) {
        document.getElementById('oauthToken').value=data.oauth_token;
        document.getElementById('oauthVerifier').value=data.oauth_verifier;
        document.getElementById('checkoutUrl').value=data.checkout_resource_url;
        
        //redirect
        window.location.href = "/masterpassResponse?oauth_token=" + data.oauth_token + "&oauth_verifier=" + data.oauth_verifier + "&checkout_resource_url=" + data.checkout_resource_url;
    }
    function onCancel() {
        // do something to tell you the cardholder cancelled
        alert('cancelled');
    }
    function onFailure() {
        // do something to tell you things have gone wrong
        alert('failure');
    }
</script>

<div class="col-9">
    <div class="row">
        <div class="contents col-12">
            <div class="col-md-7">
                <h3>Masterpass</h3>
                <img id="masterpass-button" src="https://static.masterpass.com/dyn/img/btn/global/mp_chk_btn_147x034px.svg" onclick="launchMasterpass();"/>
                <div id="oauthToken"></div>
                <div id="oauthVerifier"></div>
                <div id="checkoutUrl"></div>
            </div>
        </div>
    </div> 
</div>

Documents/Banks/Alliance/CC/MPGS/Views/Payment/PayWithPayPal.cshtml
@using gateway_csharp_sample_code.Gateway
@model gateway_csharp_sample_code.Gateway.GatewayApiRequest

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers


<script type="text/javascript">
    var DotNetSample = {
        operation: function() {
            return "INITIATE_BROWSER_PAYMENT";
        },
        endpoint: function() {
            return "processPaymentWithPayPal";
        },
        secureIdResponseUrl: function() {
            return null;
        }
    };
</script>
<!-- APPLY CLICK-JACKING STYLING AND HIDE CONTENTS OF THE PAGE -->
<style id="antiClickjack">body{display:none !important;}</style>
<!-- INCLUDE SESSION.JS JAVASCRIPT LIBRARY -->
<script src="@ViewBag.JavascriptSessionUrl"></script>

@using(Html.BeginForm("processPaymentWithPayPal", "PaymentApi", FormMethod.Post, new {@class="col-9 form-horizontal"})){
            <div class="contents col-12">
                <div class="col-md-12">
                    <h3>Pay with PayPal</h3>
                    <div class="alert alert-warning" role="alert">
                        <p>
                            <strong>NOTE:</strong> You can also do an authorization via PayPal, 
                            depending on your merchant settings.
                        </p>
                        <p> 
                            You can access full integration guidelines 
                            <a href="@ViewBag.DocumentationPayPal" target="_blank"> here</a>. 
                        <p/>
                    </div>                
                    <div class="mb-4" >
                        <h6>Order details</h6>
                    <div class="form-group">
                            <label for='order-id'>Order ID:</label>
                            <input asp-for="OrderId" type="text" id="order-id" class="form-control input-md">
                        </div>
                    <div class="form-group">
                            <label for='order-amount'>Order amount:</label>
                            <input asp-for="OrderAmount" type="text" id="order-amount" class="form-control input-md" maxlength="14">
                        </div>
                    <div class="form-group">
                            <label for='order-currency'>Order currency:</label>
                            <input asp-for="OrderCurrency" type="text" id="order-currency" class="form-control input-md" maxlength="3">
                        </div>
                    <div class="form-group">
                            <label for='order-description'>Description:</label>
                            <input asp-for="OrderDescription" type="text" id="order-description" class="form-control input-md" maxlength="127">
                        </div>
                    <div class="form-group">
                            <label for='transaction-id'>Transaction ID:</label>
                            <input asp-for="TransactionId" type="text" id="transaction-id" class="form-control input-md">
                        </div>
                    </div>
                    <button type="submit" class="mt-4 btn btn-primary" id="payButton">Pay with PayPal</button>
                </div>
            </div>
}
<script src="/js/hostedSession.js"></script>

Documents/Banks/Alliance/CC/MPGS/Views/Payment/PayWithUnionPay.cshtml
@using gateway_csharp_sample_code.Gateway
@model gateway_csharp_sample_code.Gateway.GatewayApiRequest

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers


<script type="text/javascript">
    var DotNetSample = {
        operation: function() {
            return "INITIATE_BROWSER_PAYMENT";
        },
        endpoint: function() {
            return "processPaymentWithUnionPay";
        },
        secureIdResponseUrl: function() {
            return null;
        }
    };
</script>
<!-- APPLY CLICK-JACKING STYLING AND HIDE CONTENTS OF THE PAGE -->
<style id="antiClickjack">body{display:none !important;}</style>
<!-- INCLUDE SESSION.JS JAVASCRIPT LIBRARY -->
<script src="@ViewBag.JavascriptSessionUrl"></script>

@using(Html.BeginForm("processPaymentWithUnionPay", "PaymentApi", FormMethod.Post, new {@class="col-9 form-horizontal"})){
        <div class="row">
            <div class="contents col-12">
                <div class="col-md-12">
                    <h3>Pay with UnionPay SecurePay</h3>
                    <div class="alert alert-warning" role="alert">
                        <p><strong>NOTE:</strong> You can also do an authorization via SecurePay, 
                        <br>depending on your merchant settings.</p>
                        <p>You can access test card numbers <a href="@ViewBag.DocumentationUnionPay" target="_blank">here</a>.<p/>
                    </div>                
                    <div class="mb-4" >
                        <h6>Order details</h6>
                    <div class="form-group">
                            <label for='order-id'>Order ID:</label>
                            <input asp-for="OrderId" type="text" id="order-id" class="form-control input-md">
                        </div>
                    <div class="form-group">
                            <label for='order-amount'>Order amount:</label>
                            <input asp-for="OrderAmount" type="text" id="order-amount" class="form-control input-md" maxlength="14">
                        </div>
                    <div class="form-group">
                            <label for='order-currency'>Order currency:</label>
                            <input asp-for="OrderCurrency" type="text" id="order-currency" class="form-control input-md" maxlength="3">
                        </div>
                    <div class="form-group">
                            <label for='order-description'>Description:</label>
                            <input asp-for="OrderDescription" type="text" id="order-description" class="form-control input-md" maxlength="127">
                        </div>
                    <div class="form-group">
                            <label for='transaction-id'>Transaction ID:</label>
                            <input asp-for="TransactionId" type="text" id="transaction-id" class="form-control input-md">
                        </div>
                    </div>
                    <button type="submit" class="mt-4 btn btn-primary" id="payButton">Pay with SecurePay</button>
                </div>
            </div>
        </div>
}
<script src="/js/hostedSession.js"></script>

Documents/Banks/Alliance/CC/MPGS/Views/Payment/Refund.cshtml
@using gateway_csharp_sample_code.Gateway
@model gateway_csharp_sample_code.Gateway.GatewayApiRequest

<div class="col-9">
    <div class="row">
        <form class="col-12 form-horizontal" asp-controller="PaymentApi" asp-action="process" method="post">
            <h3>Refund</h3>
            <div class="alert alert-warning" role="alert">
                This API operation is typically not a browser initiated action. However, we are calling this action from browser only as a reference to get an idea of how it can be done through your application.
            </div>
            <fieldset>
                <input asp-for="TransactionId" id="transactionId" type="hidden" />
                <input asp-for="ApiOperation" id="apiOperation" type="hidden" />
                <input asp-for="ApiMethod" id="apiMethod" type="hidden" />
                <div class="form-group">
                    <label  for="order-id">Order ID</label>
                    <input asp-for="OrderId" id="order-id" type="text" placeholder="[Order ID for existing order]" class="form-control input-md" required=""/>
                </div>
                <div class="form-group">
                    <label  for="transaction-amount">Amount</label>
                    <input asp-for="TransactionAmount" id="transaction-amount" type="text" placeholder="[Amount less than or equal to the transaction amount]" class="form-control input-md" required=""/>                      
                </div>
                <div class="form-group">
                    <label for="transaction-currency">Currency</label>
                    <input asp-for="TransactionCurrency" id="transaction-currency" type="text" placeholder="[Currency from existing order]" class="form-control input-md" required=""/>
                </div>
                <div class="form-group">
                    <button id="process" name="process" class="btn btn-primary">Process Refund</button>
                </div>
            </fieldset>
        </form>
    </div> 
</div>

Documents/Banks/Alliance/CC/MPGS/Views/Payment/Void.cshtml
@using gateway_csharp_sample_code.Gateway
@model gateway_csharp_sample_code.Gateway.GatewayApiRequest

<div class="col-9">
    <div class="row">
        <form class="col-12 form-horizontal" asp-controller="PaymentApi" asp-action="process" method="post">
            <h3>Void</h3>
            <div class="alert alert-warning" role="alert">
                This API operation is typically not a browser initiated action. However, we are calling this action from browser only as a reference to get an idea of how it can be done through your application.
            </div>
            <fieldset>
                <input asp-for="TransactionId" id="transactionId" type="hidden" />
                <input asp-for="ApiOperation" id="apiOperation" type="hidden" />
                <input asp-for="ApiMethod" id="apiMethod" type="hidden" />
                <div class="form-group">
                    <label for="order-id">Order ID</label>
                        <input asp-for="OrderId" id="order-id" type="text" placeholder="[Order ID from existing transaction]" class="form-control input-md" required=""/>
                </div>
                <div class="form-group">
                    <label for="target-transaction-id">Target Transaction ID</label>
                        <input asp-for="TargetTransactionId" id="target-transaction-id" type="text" placeholder="[Transaction ID from existing transaction]" class="form-control input-md" required=""/>
                </div>
                <div class="form-group">
                   <button id="process" name="process" class="btn btn-primary">Process Void</button>
                </div>
            </fieldset>
        </form>
    </div> <!-- row -->
</div>